services:
  # The PostgreSQL Database
  - name: me-api-db
    type: postgres
    psqlVersion: 15
    plan: free

  # The Django Web Service
  - name: me-api-backend
    type: web
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: me-api-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will generate a random secret key
      - key: WEB_CONCURRENCY
        value: 4